//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceIsRightParty.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PriceIsRightParty.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CliffhangerRemixBass.mp3.
        /// </summary>
        internal static string CliffBassFilename {
            get {
                return ResourceManager.GetString("CliffBassFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CliffhangerRemixEuro.mp3.
        /// </summary>
        internal static string CliffEuroFilename {
            get {
                return ResourceManager.GetString("CliffEuroFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliffhanger.mp3.
        /// </summary>
        internal static string CliffFilename {
            get {
                return ResourceManager.GetString("CliffFilename", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap CliffhangerBackground {
            get {
                object obj = ResourceManager.GetObject("CliffhangerBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Climber {
            get {
                object obj = ResourceManager.GetObject("Climber", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream crash {
            get {
                return ResourceManager.GetStream("crash", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap GradientBackground {
            get {
                object obj = ResourceManager.GetObject("GradientBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \Music\.
        /// </summary>
        internal static string MusicPath {
            get {
                return ResourceManager.GetString("MusicPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PiRBeatRemix.mp3.
        /// </summary>
        internal static string PiRBeatFilename {
            get {
                return ResourceManager.GetString("PiRBeatFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PiR.mp3.
        /// </summary>
        internal static string PiRFilename {
            get {
                return ResourceManager.GetString("PiRFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PiRGrooveRemix.mp3.
        /// </summary>
        internal static string PiRGrooveFilename {
            get {
                return ResourceManager.GetString("PiRGrooveFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PiRModernRemix.mp3.
        /// </summary>
        internal static string PiRModernFilename {
            get {
                return ResourceManager.GetString("PiRModernFilename", resourceCulture);
            }
        }
    }
}
